.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. blemflark_qt test_blemflark_qt
clean: FORCE
	$(MAKE) -C .. blemflark_qt_clean test_blemflark_qt_clean
check: FORCE
	$(MAKE) -C .. test_blemflark_qt_check
blemflark-qt blemflark-qt.exe: FORCE
	 $(MAKE) -C .. blemflark_qt
